---
ID: "38c5f327-dff0-4436-b793-b1e578b5b91b"
Parent: "1d68c5cd-444d-451c-8f76-33c0824eb705"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Verticurl/Global/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210714T164823Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
