---
ID: "10fc050c-aae8-4c51-b43a-67e92b5b5ca8"
Parent: "d684a2fa-eaee-428b-a7a5-b19792588ccd"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: /sitecore/layout/Renderings/Project/Trn/Custom Field Serializer/ApiUrlSettings
DB: master
SharedFields:
- ID: "037fe404-dd19-4bf7-8e30-4dadf68b27b0"
  Hint: componentName
  Value: ApiUrlSettings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210719T092738Z
