---
ID: "8825db4e-da3a-4d2f-a863-f17607445250"
Parent: "92b6789a-faca-4de0-be6a-7128a13a7bb5"
Template: "92b6789a-faca-4de0-be6a-7128a13a7bb5"
Path: /sitecore/templates/Feature/Trn/Pages/PageNotFound/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{CB78263B-948B-46F6-983D-F4B0DE343F2B}">
        <r
          id="{63472A98-054F-4D7E-9FF8-50683AF3A2ED}"
          ph="main"
          uid="{0D747B19-B219-4678-847B-2CB3CC0F9082}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210705T110212Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
