---
ID: "de393017-3086-484c-8852-c9764b10d7fd"
Parent: "a063fe99-a41d-47b6-ab1b-7b47c6dff741"
Template: "a063fe99-a41d-47b6-ab1b-7b47c6dff741"
Path: /sitecore/templates/Feature/Trn/Content/Gallery/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210609T084132Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
