---
ID: "30a38803-3d24-431d-813b-73613fcc674c"
Parent: "18ce5a5f-5d43-4c53-a37e-ce394b0fee44"
Template: "18ce5a5f-5d43-4c53-a37e-ce394b0fee44"
Path: /sitecore/templates/Project/Trn/Pages/SessionAbandonTest/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{C79C6BEB-CCCB-4B35-A980-6E36EAFB0A4C}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210623T154900Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
