---
ID: "53329d61-6991-4f84-af36-ad7e01dd19e2"
Parent: "c59eab6d-80d9-428e-b61a-eef9fcab39c0"
Template: "c59eab6d-80d9-428e-b61a-eef9fcab39c0"
Path: /sitecore/templates/Feature/Trn/Folders/AwardsFolder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{61072321-D38E-45E2-B50D-CC913FB7264F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210517T165051Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
