---
ID: "c253feb9-a29d-4972-8197-1520fec9d31b"
Parent: "cc163750-e45c-47a4-b48d-a1848f954080"
Template: "612a5930-b99b-4528-b142-475c8b8104e0"
Path: "/sitecore/content/anna-university/Home/Navigation/Services"
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 150
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210714T041008Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "bb1b5fb5-e67a-4f97-8735-14ef6c4b5056"
      Hint: Title
      Value: Services
