---
ID: "e87ebd38-bd69-43ad-81dd-ddf4b4f8c346"
Parent: "cea87d50-ec25-48f7-83f9-f744bd416df8"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Verticurl/Master/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210714T164823Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
