---
ID: "23d345d0-9376-4778-ae94-28e0c765435c"
Parent: "292ede91-d18b-4745-be76-e24cd8aa7543"
Template: "292ede91-d18b-4745-be76-e24cd8aa7543"
Path: /sitecore/templates/Feature/Trn/Content/StandardGallery/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210604T110826Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
