---
ID: "1db3aad2-aec4-491d-841c-28f4a45ea6e4"
Parent: "1305f88a-5eaf-4c6b-9491-1854d312b071"
Template: "1305f88a-5eaf-4c6b-9491-1854d312b071"
Path: /sitecore/templates/Project/Verticurl/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210714T164658Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
